Repository koanbockFH/SplitBuddy, pull requests merged in 2019-05, with the labels that each got.

#62 Bugfix teilnehmer gruppe edit
  includes/controllers/LoginController.php
  includes/views/teilnehmer.php
  js/indvGruppe.js
  js/teilnehmer.js
Labels: bug

#61 Design überarbeitung
  includes/controllers/GruppenController.php
  includes/views/addProject.php
  includes/views/basisinformation.php
  includes/views/einstellungen.php
  includes/views/ergebnis.php
  includes/views/login.php
  includes/views/meineGruppen.php
  includes/views/register.php
  includes/views/registrationComplete.php
  includes/views/teilnehmer.php
  scss/_base.scss
  scss/_colors.scss
  scss/_common.scss
  scss/_einstellungen.scss
  scss/_login_reg.scss
  scss/addProject.scss
  scss/ergebnis.scss
  scss/login.scss
  scss/meineGruppen.scss
  scss/standard.scss
Labels: enhancement

#59 Index
  images/hintergrund.jpg
  includes/views/index.php
  includes/views/parts/header.php
  scss/index.scss
Labels: enhancement

#64 Aufteilung
  includes/models/Teilnehmer.php
  includes/repository/TeilnehmerRepository.php
  includes/restservices/ProjektService.php
Labels: enhancement

#65 Bugfix teilnehmer gruppen
  js/indvGruppe.js
  js/teilnehmer.js
Labels: bug

#66 Bugfix db
  includes/models/Gruppe.php
  includes/models/Projekt.php
  includes/restservices/ProjektService.php
Labels: bug

#67 Release Docker angepasst
  Dockerfile
Labels: Change Request
