Repository koanbockFH/SplitBuddy, pull requests merged in 2019-04, with the labels that each got.

#35 Bugfix Footer Position
  includes/views/parts/footer.php
  includes/views/parts/header.php
  scss/_base.scss
Labels: bug

#33 Register
  includes/config.php
  includes/controllers/RegisterController.php
  includes/routes.php
  includes/views/parts/footer.php
  includes/views/parts/header.php
  includes/views/register.php
  js/validateRegister.js
  scss/_colors.scss
  scss/_login_reg.scss
  scss/register.scss
Labels: enhancement

#31 Datenbank initialisiert #18
  db_data/init.sql
Labels: enhancement

#34 Basisinf einstellungen design
  config.rb
  includes/views/basisinformation.php
  includes/views/einstellungen.php
  includes/views/parts/footer.php
  includes/views/parts/header.php
  js/einstellungen.js
  scss/_colors.scss
  scss/basisinformation.scss
  scss/einstellungen.scss
Labels: enhancement

#43 ReadMe Angepasst
  README.md
Labels: Change Request

#41 Indv gruppe design
  includes/views/indvGruppe.php
  js/indvGruppe.js
Labels: enhancement

#40 Projekt anlage
  Dockerfile
  config.rb
  docker-debug.yml
  includes/classes/View.php
  includes/config.php
  includes/controllers/AddProjectController.php
  includes/routes.php
  includes/views/addProject.php
  includes/views/basisinformation.php
  includes/views/einstellungen.php
  includes/views/indvGruppe.php
  includes/views/parts/footer.php
  includes/views/parts/header.php
  includes/views/teilnehmer.php
  js/CardNavigation.js
  js/addProject.js
  js/einstellungen.js
  js/indvGruppe.js
  js/teilnehmer.js
  scss/_base.scss
  scss/_colors.scss
  scss/_common.scss
  scss/_einstellungen.scss
  scss/_login_reg.scss
  scss/_navigation.scss
  scss/addProject.scss
Labels: enhancement

#45 updated database #44
  db_data/init.sql
Labels: Change Request

#42 Registration backend
  includes/classes/Controller.php
  includes/classes/Database.php
  includes/classes/JSON.php
  includes/classes/Route.php
  includes/classes/View.php
  includes/controllers/IndexController.php
  includes/controllers/LoginController.php
  includes/controllers/LogoutController.php
  includes/controllers/RegisterController.php
  includes/controllers/RegistrationCompleteController.php
  includes/dbconfig.php
  includes/initialize.php
  includes/models/SessionCached.php
  includes/models/SessionUser.php
  includes/repository/BaseRepository.php
  includes/repository/UserRepository.php
  includes/routes.php
  includes/views/login.php
  includes/views/logout.php
  includes/views/parts/footer.php
  includes/views/parts/header.php
  includes/views/register.php
  includes/views/registrationComplete.php
  index.php
  js/login.js
  js/register.js
  js/validateRegister.js
  scss/standard.scss
Labels: enhancement

#37 Ergebnis
  .htaccess
  api.php
  includes/controllers/AddProjectController.php
  includes/controllers/ErgebnisController.php
  includes/initialize.php
  includes/models/Geschlecht.php
  includes/models/Gruppe.php
  includes/models/Projekt.php
  includes/models/SessionUser.php
  includes/models/Teilnehmer.php
  includes/repository/GeschlechtRepository.php
  includes/repository/GruppeRepository.php
  includes/repository/ProjektRepository.php
  includes/repository/TeilnehmerRepository.php
  includes/restservices.php
  includes/restservices/BaseService.php
  includes/restservices/ProjektService.php
  includes/routes.php
  includes/views/addProject.php
  includes/views/ergebnis.php
  includes/views/index.php
  includes/views/login.php
  includes/views/logout.php
  includes/views/parts/header.php
  includes/views/register.php
  includes/views/registrationComplete.php
  includes/views/teilnehmer.php
  index.php
  js/addProject.js
  scss/ergebnis.scss
  scss/index.scss
Labels: enhancement

#49 fixed bug #48
  js/validateRegister.js
Labels: bug

#47 Registration backend validierung
  includes/config.php
  includes/repository/UserRepository.php
Labels: enhancement

#52 Refactoring
  includes/classes/Route.php
  includes/controllers/AddProjectController.php
  includes/controllers/BaseController.php
  includes/controllers/ErgebnisController.php
  includes/controllers/IndexController.php
  includes/controllers/LoginController.php
  includes/controllers/LogoutController.php
  includes/controllers/RegisterController.php
  includes/controllers/RegistrationCompleteController.php
  includes/models/Geschlecht.php
  includes/models/Gruppe.php
  includes/models/Projekt.php
  includes/models/Teilnehmer.php
  includes/repository/BaseCRUDRepository.php
  includes/repository/BaseRepository.php
  includes/repository/GeschlechtRepository.php
  includes/repository/GruppeRepository.php
  includes/repository/ProjektRepository.php
  includes/repository/TeilnehmerRepository.php
  includes/repository/UserRepository.php
  includes/restservices/ProjektService.php
  includes/routes.php
  js/addProject.js
  js/login.js
  js/register.js
  js/teilnehmer.js
Labels: enhancement

#51 created 404 page #50
  images/404.png
  includes/views/404.php
  scss/404.scss
Labels: enhancement

#54 Meine gruppen
  includes/controllers/ErgebnisController.php
  includes/controllers/GruppenController.php
  includes/repository/ProjektRepository.php
  includes/routes.php
  includes/views/ergebnis.php
  includes/views/login.php
  includes/views/meineGruppen.php
  includes/views/parts/footer.php
  includes/views/parts/header.php
  scss/_common.scss
  scss/login.scss
  scss/meineGruppen.scss
Labels: enhancement

#56 Teilnehmer Projektreferenz entfernt
  db_data/init.sql
  includes/models/Teilnehmer.php
  includes/repository/TeilnehmerRepository.php
Labels: Change Request

#58 Fixed Teilnehmer SQL Query #57
  includes/repository/TeilnehmerRepository.php
Labels: bug
